# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 581863ebd9799c2cccf69c5642acd7bda510b8036d1c2bbf28c619aef2bb7ac73fa2a995a567916b11e4e48651ca91b322e12d0cdd9cc2cadad1633ff8ef80f7

test:
  secret_key_base: 5cb2534d36bdee6f01ffe7ee2b9e18e587341b0933818125bc287dfe2f2bd1016ca075a8b2ed476230364cda2841d5f7c3d69ec340fefd6cefcaf33a4a11d16f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
